# CI for NVIP

name: Node CI

on: [push]

env:
  AWS_REGION: 'us-east-1'
  ANGULAR_CLI_VERSION: '17.2.3'

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Build and run tests
        run: |
          npm install -g @angular/cli
          npm install
          npm test -- --watch=false --browsers=ChromeHeadless

# Deploy crawler component project to container registry
  staging-deploy:
    runs-on: ubuntu-latest
    environment: staging
    needs: build-test
    if: ${{ success() && github.ref == 'refs/heads/master' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Build
        run: |
          npm install -g @angular/cli
          npm install --force
          ng build angular-ui --configuration=staging
      - name: Deploy to S3
        if: ${{ success() && github.ref == 'refs/heads/master' }}
        run: |
          aws s3 sync ./dist/angular-ui s3://${{ vars.S3_BUCKET_NAME }}

  # Deploy crawler component project to container registry
  production-deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: staging-deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Build
        run: |
          npm install -g @angular/cli
          npm install --force
          ng build angular-ui --configuration=production
      - name: Deploy to S3
        if: ${{ success() && github.ref == 'refs/heads/master' }}
        run: |
          aws s3 sync ./dist/angular-ui s3://${{ vars.S3_BUCKET_NAME }}
